const WEBHOOK_URL_BASE = 'https://api.getcontexto.com';

interface WebhookConfig {
  apiKey: string;
  contextEnabled: boolean;
}

interface WebhookPayload {
  event: {
    type: string;
    action: string;
  };
  sessionKey: string;
  timestamp: string;
  context: Record<string, unknown>;
  agent?: Record<string, unknown>;
  data?: Record<string, unknown>;
}

async function sendWebhook(config: WebhookConfig, payload: WebhookPayload, logger: any): Promise<void> {
  try {
    const response = await fetch(`${WEBHOOK_URL_BASE}/v1/webhooks/events`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${config.apiKey}`,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const body = await response.text().catch(() => '(no body)');
      logger.warn(`[webhook] HTTP ${response.status}: ${response.statusText} — body: ${body}`);
    } else {
      logger.info(`[webhook] OK ${response.status} for ${payload.event.type}:${payload.event.action}`);
    }
  } catch (err) {
    logger.warn(`[webhook] Failed to send: ${err instanceof Error ? err.message : String(err)}`);
  }
}

function buildPayload(
  type: string,
  action: string,
  sessionKey: string,
  context: Record<string, unknown>,
  agent?: Record<string, unknown>,
  data?: Record<string, unknown>
): WebhookPayload {
  return {
    event: { type, action },
    sessionKey,
    timestamp: new Date().toISOString(),
    context,
    agent,
    data,
  };
}

const webhookPlugin = {
  id: '@ekai/contexto',
  name: 'Mind Map',
  description: 'Sends OpenClaw conversation events to a webhook API',

  configSchema: {
    type: 'object',
    properties: {
      apiKey: { type: 'string' },
      contextEnabled: { type: 'boolean', default: false },
    },
  },

  register(api: any) {
    const config: WebhookConfig = {
      apiKey: api.pluginConfig?.apiKey,
      contextEnabled: api.pluginConfig?.contextEnabled ?? false,
    };

    const logger = api.logger;

    if (!config.apiKey) {
      logger.warn('[webhook] Missing apiKey - events will not be sent');
    }

    logger.info(`[webhook] Plugin registered, baseUrl: ${WEBHOOK_URL_BASE}`);

    // --- User input (raw inbound message) ---
    // Using api.on() which pushes directly to typedHooks (runtime).
    // api.registerHook() only adds to the catalog and requires config.hooks.internal.enabled.
    api.on('message_received', async (event: any, ctx: any) => {
      if (!config.apiKey) return;

      const sessionKey = ctx?.sessionKey || 'unknown';
      const payload = buildPayload(
        'message',
        'received',
        sessionKey,
        {
          from: event?.from,
          timestamp: event?.timestamp,
          provider: event?.metadata?.provider,
          surface: event?.metadata?.surface,
          threadId: event?.metadata?.threadId,
          channelName: event?.metadata?.channelName,
          senderId: event?.metadata?.senderId,
          senderName: event?.metadata?.senderName,
          senderUsername: event?.metadata?.senderUsername,
          messageId: event?.metadata?.messageId,
        },
        undefined,
        {
          content: event?.content,
        }
      );

      sendWebhook(config, payload, logger);
    });

  // --- LLM Raw Output (as soon as the model finishes generating) ---
  api.on('llm_output', async (event: any, ctx: any) => {
    if (!config.apiKey) return;

    // ctx usually contains the session metadata in the Plugin API
    const sessionKey = ctx?.sessionKey || 'unknown';

    const payload = buildPayload(
      'llm',           // Type: LLM generation
      'output',        // Action: model output received
      sessionKey,
      {
        model: event?.model,            // The model used (e.g., 'gpt-4o')
        usage: {
          prompt_tokens: event?.usage?.promptTokens,
          completion_tokens: event?.usage?.completionTokens,
          total_tokens: event?.usage?.totalTokens
        }
      },
      undefined,
      {
        content: event?.assistantText,  // The actual text generated by the AI
      }
    );

    sendWebhook(config, payload, logger);
  });

    // --- Compaction events ---
    api.on('before_compaction', async (event: any, ctx: any) => {
      if (!config.apiKey) return;

      const sessionKey = ctx?.sessionKey || 'unknown';
      const payload = buildPayload(
        'session',
        'compact:before',
        sessionKey,
        {
          messageCount: event?.messageCount,
          tokenCount: event?.tokenCount,
        }
      );

      sendWebhook(config, payload, logger);
    });

    api.on('after_compaction', async (event: any, ctx: any) => {
      if (!config.apiKey) return;

      const sessionKey = ctx?.sessionKey || 'unknown';
      const payload = buildPayload(
        'session',
        'compact:after',
        sessionKey,
        {
          summary: event?.summary?.slice(0, 2000),
          originalMessageCount: event?.originalMessageCount,
          compactedMessageCount: event?.compactedMessageCount,
        }
      );

      sendWebhook(config, payload, logger);
    });

    logger.info('[webhook] All hooks registered via api.on()');
  },
};

export default webhookPlugin;